CREATE TABLE ods.mh_obligaciones
(
	anho character varying
	, codigoNivel character varying
	, descripcionNivel character varying
	, codigoEntidad character varying
	, descripcionEntidad character varying
	, codigoUaf character varying
	, descripcionUaf character varying
	, numeroObligacion character varying
	, codigoContratacion character varying
	, tipoComprobante character varying
	, numeroComprobante character varying
	, fechaComprobante character varying
	, numeroTimbrado character varying
	, ruc character varying
	, razonSocial character varying
	, grupoObjetoGasto character varying
	, codigoGrupoObjeto character varying
	, subgrupoObjetoGasto character varying
	, codigoSubgrupoObjeto character varying
	, objetoGasto character varying
	, codigoObjeto character varying
	, codigoFuenteFinanciamiento character varying
	, fuenteFinanciamiento character varying
	, monto character varying
	, deduccionIva character varying
	, deduccionRenta character varying
	, deduccionDncp character varying
	, deduccionIncumplimiento character varying
	, deduccionOtros character varying
	, fechaElaboracion character varying
	, fechaAprobacion character varying
	, fechaCorreccion character varying
	, fechaAnulacion character varying
	, anhoSTR character varying
	, concepto character varying
	, codigoMoneda character varying
	, descripcionMoneda character varying
	, tipoCambio character varying
	, numeroCdp character varying
	, numeroStr character varying
	, lineaPresupuestaria character varying
	, paginaDncp character varying
	, contratoDncp character varying
	, apiDncp character varying
	, anhoCorte character varying
	, mesCorte character varying
	, fechaCorte character varying
	, descripcionComprobante character varying
)