drop table br_obligacion_contrato;
drop table br_obligacion_str;
truncate table dim_categoria_dncp cascade;
truncate table dim_clasificador_control_financiero cascade;
truncate table dim_clasificador_entidad cascade;
truncate table dim_clasificador_fuente_financiamiento cascade;
truncate table dim_clasificador_funcion cascade;
truncate table dim_clasificador_geografico cascade;
truncate table dim_clasificador_objeto_gasto cascade;
truncate table dim_clasificador_programa cascade;
truncate table dim_cuenta_bancaria cascade;
truncate table dim_junk_contrato cascade;
truncate table dim_junk_obligacion cascade;
truncate table dim_junk_ot cascade;
truncate table dim_junk_str cascade;
truncate table dim_proveedor cascade;
truncate table dim_tiempo cascade;
truncate table dim_tipo_procedimiento_dncp cascade;
truncate table fact_contrato cascade;
truncate table fact_obligacion cascade;
truncate table fact_ot cascade;
truncate table fact_str cascade;