CREATE TABLE ods.mh_pgn
(
	anio character varying
	, mes character varying
	, codigoNivel character varying
	, descripcionNivel character varying
	, codigoEntidad character varying
	, descripcionEntidad character varying
	, codigoUnidadResponsable character varying
	, descripcionUnidadResponsable character varying
	, codigoTipoPresupuesto character varying
	, descripcionTipoPresupuesto character varying
	, codigoPrograma character varying
	, descripcionPrograma character varying
	, codigoSubprograma character varying
	, descripcionSubprograma character varying
	, codigoProyecto character varying
	, descripcionProyecto character varying
	, codigoFinalidad character varying
	, finalidad character varying
	, codigoFuncion character varying
	, funcion character varying
	, codigoSubfuncion character varying
	, subfuncion character varying
	, grupoEconomico character varying
	, subgrupoEconomico character varying
	, categoriaEconomica character varying
	, codigoFuenteFinanciamiento character varying
	, descripcionFuenteFinanciamiento character varying
	, codigoGrupoObjetoGasto character varying
	, grupoObjetoGasto character varying
	, codigoSubgrupoObjetoGasto character varying
	, subgrupoObjetoGasto character varying
	, codigoObjetoGasto character varying
	, objetoGasto character varying
	, codigoOrganismoFinanciador character varying
	, descripcionOrganismoFinanciador character varying
	, codigoDepartamento character varying
	, departamento character varying
	, codigoUAF character varying
	, descripcionUAF character varying
	, codigoNivelFinanciero character varying
	, nombreNivelFinanciero character varying
	, presupuestoInicialAprobado character varying
	, montoVigente character varying
	, montoPlanFinancieroVigente character varying
	, montoEjecutado character varying
	, montoTransferido character varying
	, montoPagado character varying
	, mesCorte character varying
	, anioCorte character varying
	, fechaCorte character varying
)