CREATE TABLE ods.dncp_convocatorias
(
	id character varying
	, planificacion_id character varying
	, id_llamado character varying
	, nombre_licitacion character varying
	, convocante character varying
	, codigo_sicp character varying
	, categoria_id character varying
	, categoria_codigo character varying
	, categoria character varying
	, tipo_procedimiento_id character varying
	, tipo_procedimiento_codigo character varying
	, tipo_procedimiento character varying
	, _estado character varying
	, estado character varying
	, _tipo_garantia_oferta character varying
	, tipo_garantia_oferta character varying
	, mantenimiento_oferta character varying
	, seguro_resp_prof character varying
	, _metodo_seleccion character varying
	, metodo_seleccion character varying
	, fecha_publicacion character varying
	, _sistema_adjudicacion character varying
	, sistema_adjudicacion character varying
	, _forma_pago character varying
	, forma_pago character varying
	, monto_estimado character varying
	, _moneda character varying
	, moneda character varying
	, fuente_financiamiento character varying
	, anticipo character varying
	, plazo_entrega_adquisicion character varying
	, lugar_entrega_adquisicion character varying
	, vigencia_contrato character varying
	, nombre_contacto character varying
	, cargo_contacto character varying
	, telefono_contacto character varying
	, email_contacto character varying
	, fecha_junta_aclaracion character varying
	, lugar_junta_aclaracion character varying
	, lugar_consulta character varying
	, fecha_tope_consulta character varying
	, fecha_tope_respuesta character varying
	, lugar_entrega_oferta character varying
	, fecha_entrega_oferta character varying
	, lugar_apertura_oferta character varying
	, fecha_apertura_oferta character varying
	, fecha_inicio_propuesta character varying
	, fecha_cierre_propuesta character varying
	, fecha_etapa_competitiva character varying
	, fecha_cierre_subasta character varying
	, observaciones character varying
	, restricciones character varying
	, organismo_financiador_id character varying
	, organismo_financiador character varying
	, cantidad_llamados_relacionados character varying
	, url character varying
)